# Copyright 2011 The Misu Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/Popog/misu/component
GOFILES=\
	base.go\
	collection.go\
	component.go\
	registration.go

include $(GOROOT)/src/Make.pkg
